### PR TITLE
Make ActionController::Caching::Sweeper class thread safe

### LINKED ISSUE #71: ActionController::Caching::Sweeper controller instance is not thread safe
Hello,

We're using this gem to manage and clean the cache of our site. Thank you for it! 

We use puma as the web server for Rails. In production, we configure it to use several threads. Some time ago, we started to get exceptions of an undefined `expire_action` method:

```undefined method `expire_action' for #<ReleaseSweeper:0x000000073b69b8 @_routes=nil, @controller=nil> Did you mean? expire_api_actions```

We've some loops in our sweeper and at some point, the `@controller` variable is lost between the different puma threads.

To solve this issue, we've applied this monkey patch from this [comment](https://github.com/rails/rails/issues/643#issuecomment-3125019).

```
# Fix https://github.com/rails/rails/issues/643
module ActionController::Caching
  class Sweeper < ActiveRecord::Observer
    def controller
      Thread.current["#{self.class.name}_controller"]
    end

    def controller=(controller)
      Thread.current["#{self.class.name}_controller"] = controller
    end

  private

    def method_missing(method, *arguments, &block)
      return if controller.nil?
      controller.__send__(method, *arguments, &block)
    end
  end
end
```

I see the comment is from 2011, but this code didn't end in the gem. So, I don't know if there's any reason for not adding this code. 

Should I create a pull request?

### PR DESCRIPTION
**Pull request by Angelmmiguel**
The current implementation of `ActionController::Caching::Sweeper` is not Thread safe and it may cause issues in multi-thread environments. The problem is that `@controller` variable is lost in the different Threads. For sweepers with big loops, it might cause the following error:

```
undefined method `expire_action' for #<ReleaseSweeper:0x000000073b69b8 @_routes=nil, @controller=nil>
```

## Changes

* Store the controller variable in a current Thread property
* Fix a deprecation message with minitest

This closes #71

### CODE REVIEW

**Comment by Angelmmiguel** [comment]
@rafaelfranca I'm a bit afraid of the compatibility of this PR with the current usage of the gem. I see [some](https://github.com/rails/rails-observers/issues/31) [people](https://github.com/rails/actionpack-action_caching/issues/54) [suggesting](http://www.gakshay.com/2014/03/02/calling-expire_fragment-within-rails-console/) to use `@controller ||= ActionController::Base.new` to avoid `@controller` to be `nil`. However, with these changes, the code will be different:

```
self.controller ||= ActionController::Base.new
```

**Comment by Angelmmiguel** [comment]
@rafaelfranca do I need to perform any extra change? :)

File: lib/rails/observers/action_controller/caching/sweeper.rb [hunk 1]
```diff
@@ -53,8 +59,13 @@ def callback(timing)
       end
 
       def method_missing(method, *arguments, &block)
-        return super unless @controller
-        @controller.__send__(method, *arguments, &block)
+        return super if controller.nil?
+        controller.__send__(method, *arguments, &block)
+      end
+
+      # @see https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding
```
Comment (rafaelfranca) [inline lib/rails/observers/action_controller/caching/sweeper.rb]: I think you can remove this comment

**Comment by Angelmmiguel** [comment]
Done @rafaelfranca !
